services:
  - type: web
    name: feedback-backend
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader --no-interaction || echo "No dependencies to install"
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: PHP_VERSION
        value: "8.1"
